# Generated by Django 3.1.7 on 2021-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_field', models.CharField(blank=True, max_length=255, null=True)),
                ('main1', models.ImageField(blank=True, null=True, upload_to='about/application/images')),
                ('description1', models.TextField(blank=True, null=True)),
                ('main2', models.ImageField(blank=True, null=True, upload_to='about/application/images')),
                ('description2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
