# Generated by Django 3.1.7 on 2021-03-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='main3',
            field=models.ImageField(blank=True, null=True, upload_to='about/application/images'),
        ),
    ]
