# Generated by Django 3.1.7 on 2021-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0003_auto_20210324_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
