# Generated by Django 3.1.7 on 2021-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0004_auto_20210324_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('weight_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_value', models.CharField(blank=True, max_length=50, null=True)),
                ('weft_yarn_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('weft_yarn_value', models.CharField(blank=True, max_length=50, null=True)),
                ('warp_yarn_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('warp_yarn_value', models.CharField(blank=True, max_length=50, null=True)),
                ('patern_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('patern_value', models.CharField(blank=True, max_length=50, null=True)),
                ('md_tensile_strength_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('md_tensile_strength_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd_tensile_strength_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('cd_tensile_strength_value', models.CharField(blank=True, max_length=50, null=True)),
                ('elongation_at_break_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('elongation_at_break_value', models.CharField(blank=True, max_length=50, null=True)),
                ('coathing_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('coathing_value', models.CharField(blank=True, max_length=50, null=True)),
                ('core_size_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('core_size_value', models.CharField(blank=True, max_length=50, null=True)),
                ('role_width_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('role_width_value', models.CharField(blank=True, max_length=50, null=True)),
                ('yarns_type', models.CharField(blank=True, max_length=50, null=True)),
                ('constructions', models.CharField(blank=True, max_length=50, null=True)),
                ('patterns', models.CharField(blank=True, max_length=50, null=True)),
                ('bondings', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
