# Generated by Django 3.1.7 on 2021-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='role_length_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='role_length_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
