# Generated by Django 3.1.7 on 2021-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0006_auto_20210324_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('msg1', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('msg2', models.CharField(blank=True, max_length=255, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('msg3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
