# Generated by Django 3.1.7 on 2021-03-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0008_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=255)),
                ('working_hour', models.CharField(max_length=255)),
                ('phone_nr', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
