# Generated by Django 3.1.7 on 2021-03-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0009_auto_20210324_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/bottom/images')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
