# Generated by Django 3.1.7 on 2021-03-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0010_newsfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='image',
            new_name='image1',
        ),
    ]
