# Generated by Django 3.1.7 on 2021-04-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roza', '0012_auto_20210419_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='about_model',
        ),
        migrations.RenameModel(
            old_name='Application',
            new_name='application_model',
        ),
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='contactinfo_model',
        ),
        migrations.RenameModel(
            old_name='Contacts',
            new_name='contacts_model',
        ),
        migrations.RenameModel(
            old_name='homep',
            new_name='home_model',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='product_model',
        ),
    ]
